### ISSUE TITLE
[question] Pausing a task to prompt the user

### ISSUE THREAD

**Issue by Tobbe** [keindev/tasktree#906]
Hi! This library looks really promising. Thinking of maybe using this instead of Listr.

Is it possible to add a prompt to a task?

Like, say I have a task for copying files. And then I want to stop and ask if the user wants to overwrite a file. Does Tasktree support this scenario? Do you maybe even have an example of integrating Tasktree with something like [prompts](https://www.npmjs.com/package/prompts) or [enquirer](https://www.npmjs.com/package/enquirer)?

**Comment by keindev** [comment]
No, But I think it's worth adding something like that. At the very least, it would be nice to be able to pause the task and give stdout to some user output, and then continue.

**Comment by keindev** [comment]
@Tobbe now you can use `tasktree,pause` for external output in `v7.x`.

but you need to know count of output rows for cleared its after.

```ts
/* eslint-disable */
import TaskTree from '../src/index.js';
import Enquirer from 'enquirer';

const tree = TaskTree.tree();

try {
  // start task tree log update in terminal
  tree.start();

  // create tasks
  const task1 = tree.add('{underline Task {bold #1}}');
  const task2 = tree.add('Task {bold #2}');
  const task3 = task2.add('Subtask...');
  const tpl = ':bar :rate/bps {cyan.bold :percent} :etas';
  // create progress bars
  const bars = [task3.bar(tpl), task3.bar(tpl), task3.bar(tpl)];

  // ... whatever
  let once = false;
  const promises = [50, 75, 200].map((ms, i) => {
    return new Promise(resolve => {
      const handle = setInterval(() => {
        const bar = bars[i];

        if (bar) {
          if (once) {
            if (bar.percent >= 50) {
              bar.skip();
            } else {
              bar.fail();
            }
          } else {
            once = bar.tick(Math.random() * 10).isCompleted;
          }
        }

        if (once) {
          clearInterval(handle);
          resolve();
        }
      }, ms);
    });
  });

  await Promise.all(promises);

  await tree.pause(async () => {
    const prompt = new Enquirer.Input({ name: 'username', message: 'What is your username?' });

    await prompt.run().then(answer => console.log('Username:', answer));

    // Return count of output rows if necessary to remove its from output.
    // TaskTree can't automatically detect external output rows count
    return 2;
  });

  // skip task
  task3.skip('Subtask skipped');
  // log info message in Task #2, complete task
  task2.log('Informational message').complete();
  // log warning and error in Task #1, fail it
  task1.warn('Warning message').error(new Error('Something bad happened'), true);
  // stop task tree log update
  tree.stop();
} catch (error) {
  tree.fail(error);
}

```

**Comment by Tobbe** [comment]
Thanks for implementing the `pause` function 🙏 

For my use-case I spawn an external process. I don't know how many lines it will print. But it's usually much more than what can fit on the screen.

I have a few questions

If I print one long line and the user has a very narrow terminal window, so the line wraps one or more times, do I still return `1` from `pause` callback? Or do I need to somehow detect if my output was wrapped?

Let's say the user's terminal is 20 lines tall. If my output is 32 lines, should I return `20` or `32`?
